# Site settings
title: Kinsomy Blog
SEOTitle: Kinsomy的博客 | Kinsomy Blog
header-img: img/post-bg-desk.jpg
email: fjs19960420@gmail.com
description: "code transporter"
keyword: "Kinsomy, Kinsomy Blog, Kinsomy的博客, Android, Flutter, 生活"
url: "http://kinsomyjs.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/KinsomyJS/KinsomyJS.github.io" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "代码搬运工"
sidebar-avatar: /img/avatar.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     
zhihu_username:     kinsomy
juejin_username:     5ab89278f265da23a0498d65
github_username:    kinsomyjs
# facebook_username:  kinsomy
# jianshu_username:   
#twitter_username:   




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
disqus_username: kinsomy

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID:    69d67ec785a5756f63e1                         #生成的clientID
  clientSecret:  6c95c83eb4d634a2cb7308efb3c3fefd383c02de   #生成的clientSecret
  repo:  KinsomyJS.github.io   #仓库名称
  owner:  kinsomyjs   #github用户名
  admin:  kinsomyjs
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 74c3d472b664a792fcd971da4663ca4b

# Google Analytics
# ga_track_id: ''            # Format: UA-xxxxxx-xx
# ga_domain:                # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
# friends: [
#     {
#         title: "",
#         href: ""
#     },{
#         title: "",
#         href: ""
#     },{
#         title: "",
#         href: ""
#     },{
#         title: "",
#         href: ""
#     }
# ]
